// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQLMVk65qZ87K2taizET3kHI6FIshHl7A',
    appId: '1:554161531479:web:17890e3d7ad14f5381d112',
    messagingSenderId: '554161531479',
    projectId: 'clothes-app-78078',
    authDomain: 'clothes-app-78078.firebaseapp.com',
    storageBucket: 'clothes-app-78078.appspot.com',
    measurementId: 'G-MVDJWV8MWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1JiBvJjZqoEDxWJTgtUonzG6hoPaqeFQ',
    appId: '1:554161531479:android:e51b0d27af2c336081d112',
    messagingSenderId: '554161531479',
    projectId: 'clothes-app-78078',
    storageBucket: 'clothes-app-78078.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjRK_HptSjvVHfWKeiyccNsrjJV0Kq5Ws',
    appId: '1:554161531479:ios:ab048f3d7b6740d281d112',
    messagingSenderId: '554161531479',
    projectId: 'clothes-app-78078',
    storageBucket: 'clothes-app-78078.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjRK_HptSjvVHfWKeiyccNsrjJV0Kq5Ws',
    appId: '1:554161531479:ios:2217c348ef0104ec81d112',
    messagingSenderId: '554161531479',
    projectId: 'clothes-app-78078',
    storageBucket: 'clothes-app-78078.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
